version: '3.8'

services:
  bestview-app:
    image: hamrazhakeem/bestview-app:latest
    container_name: bestview-app
    restart: always
    ports:
      - "80:10000"
    depends_on:
      - bestview-db
    env_file:
      - .env
    networks:
      - bestview-network
      
  bestview-db:
    image: postgres:13
    container_name: bestview-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks: 
      - bestview-network

volumes:
  postgres_data: 

networks:
  bestview-network: 